# Generated by Django 3.0.6 on 2020-06-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.IntegerField()),
                ('invoiceDate', models.CharField(max_length=10)),
                ('custName', models.CharField(max_length=20)),
                ('custGST', models.CharField(max_length=15)),
                ('itemName', models.CharField(max_length=15)),
                ('quantity', models.CharField(max_length=10)),
                ('pricePerUnit', models.CharField(max_length=5)),
                ('subtotal', models.CharField(max_length=8)),
                ('gstType', models.CharField(max_length=10)),
                ('gstAmount', models.CharField(max_length=5)),
                ('total', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='custGST',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='sellerGST',
            field=models.CharField(max_length=15),
        ),
    ]
