# Generated by Django 3.0.6 on 2020-06-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0002_auto_20200606_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='custName',
            field=models.CharField(max_length=25),
        ),
    ]
