# Generated by Django 3.0.6 on 2020-06-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0003_auto_20200607_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='address1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='address2',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='custName',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='sellerName',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='custName',
            field=models.CharField(max_length=35),
        ),
    ]
