# Generated by Django 3.0.6 on 2020-06-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0004_auto_20200607_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='custName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='sellerName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='custName',
            field=models.CharField(max_length=40),
        ),
    ]
