# Generated by Django 3.0.6 on 2020-06-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0005_auto_20200608_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salemodel',
            name='gstAmount',
        ),
        migrations.AddField(
            model_name='salemodel',
            name='CGST',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='GST',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='IGST',
            field=models.CharField(default='', max_length=5),
        ),
    ]
