# Generated by Django 3.0.6 on 2020-06-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0006_auto_20200612_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemodel',
            name='CGST',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='GST',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='IGST',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
