# Generated by Django 3.0.6 on 2020-06-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0007_auto_20200612_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salemodel',
            old_name='GST',
            new_name='SGST',
        ),
    ]
