# Generated by Django 3.0.6 on 2020-06-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0008_auto_20200612_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='transportName',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='invoiceDate',
            field=models.DateField(max_length=10),
        ),
    ]
