# Generated by Django 3.0.6 on 2020-06-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0010_auto_20200613_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasemodel',
            name='GST',
        ),
        migrations.RemoveField(
            model_name='salemodel',
            name='invoiceDate',
        ),
        migrations.AddField(
            model_name='purchasemodel',
            name='CGST',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='purchasemodel',
            name='IGST',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='purchasemodel',
            name='SGST',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='gstType',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='invoiceNumber',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='otherCharges',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='pricePerUnit',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='quantity',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='sellerGST',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='sellerName',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='subTotal',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='CGST',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='IGST',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='SGST',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='subtotal',
            field=models.CharField(max_length=10),
        ),
    ]
