# Generated by Django 3.0.6 on 2020-06-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0011_auto_20200625_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='invoicedate',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='invoiceDate',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
