# Generated by Django 3.0.6 on 2020-06-25 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0016_auto_20200625_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemodel',
            name='invoiceDate',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 6, 25)),
        ),
    ]
