# Generated by Django 3.0.6 on 2020-06-27 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0017_auto_20200625_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerName', models.CharField(max_length=40)),
                ('sellerGST', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='invoiceDate',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 6, 27)),
        ),
    ]
