# Generated by Django 3.0.6 on 2020-06-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0018_auto_20200627_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellermodel',
            name='GSTType',
            field=models.CharField(default='', max_length=10),
        ),
    ]
