# Generated by Django 3.0.6 on 2020-06-28 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0020_purchasemodel_itemname'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='HSN',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='purchasemodel',
            name='gstType2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='invoiceDate',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 6, 28)),
        ),
    ]
