# Generated by Django 3.0.6 on 2020-07-01 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0023_auto_20200701_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemodel',
            name='invoiceDate',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 7, 1), max_length=40, null=True),
        ),
    ]
