# Generated by Django 3.0.6 on 2020-07-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0025_auto_20200701_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salemodel',
            name='invoiceDate',
        ),
    ]
