# Generated by Django 3.0.6 on 2020-07-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0026_remove_salemodel_invoicedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='invoiceDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
