# Generated by Django 3.0.6 on 2020-07-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0028_auto_20200701_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemodel',
            name='itemName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='transportName',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
