# Generated by Django 3.0.6 on 2020-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0029_auto_20200701_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='transportGST',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
