# Generated by Django 3.0.6 on 2020-07-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0030_salemodel_transportgst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salemodel',
            old_name='transportName',
            new_name='transportNameOrVehicleNo',
        ),
    ]
