# Generated by Django 3.0.6 on 2020-07-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0031_auto_20200706_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemodel',
            name='transportGST',
            field=models.CharField(blank=True, default='-', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='transportNameOrVehicleNo',
            field=models.CharField(blank=True, default='-', max_length=25, null=True),
        ),
    ]
