# Generated by Django 3.0.6 on 2020-07-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0033_auto_20200706_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='LR_NO',
            field=models.CharField(blank=True, default='-', max_length=10),
        ),
    ]
