# Generated by Django 3.0.6 on 2020-07-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0034_salemodel_lr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemodel',
            name='LR_NO',
            field=models.CharField(blank=True, default='-', max_length=10, null=True),
        ),
    ]
