# Generated by Django 3.0.6 on 2020-09-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0036_customermodel_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='HSN_CODE',
            field=models.CharField(default=5407, max_length=4),
        ),
    ]
