# Generated by Django 3.0.6 on 2021-09-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0038_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
