# Generated by Django 3.0.6 on 2021-09-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0039_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyGST', models.CharField(default='', max_length=15)),
                ('transactionDate', models.DateField(blank=True, null=True)),
                ('ref', models.CharField(max_length=100)),
                ('crdr', models.CharField(max_length=2)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
