# Generated by Django 3.0.6 on 2024-06-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0041_transaction_partytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemodel',
            name='HSN_CODE',
            field=models.CharField(default=5407, max_length=10),
        ),
    ]
