# Generated by Django 3.2.25 on 2026-10-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceGeneration', '0042_auto_20240615_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='address1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='address2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='custName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='CGST',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='HSN',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='IGST',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='SGST',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='gstType2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='itemName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='otherCharges',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='pricePerUnit',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='sellerName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='subTotal',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='totalAmount',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='CGST',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='IGST',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='LR_NO',
            field=models.CharField(blank=True, default='-', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='SGST',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='custName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='itemName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='pricePerUnit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='quantity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='subtotal',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='total',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='transportGSTOrVehicleNumber',
            field=models.CharField(blank=True, default='-', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='transportName',
            field=models.CharField(blank=True, default='-', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='sellerName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='partyGST',
            field=models.CharField(default='', max_length=150),
        ),
    ]
