name: Renew PythonAnywhere

on:
  schedule:
    - cron: "0 10 25 * *"
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install playwright

      - run: npx playwright install chromium

      - run: node renew.js
        env:
          PA_USERNAME: ${{ secrets.PA_USERNAME }}
          PA_PASSWORD: ${{ secrets.PA_PASSWORD }}
